// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PeticionesAjaxJavaScriptFetch;

namespace PeticionesAjaxJavaScriptFetch.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20190613022736_EstudianteAjax")]
    partial class EstudianteAjax
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PeticionesAjaxJavaScriptFetch.Models.Estudiante", b =>
                {
                    b.Property<int>("id_estudiante")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("carrera")
                        .IsRequired()
                        .HasMaxLength(65);

                    b.Property<string>("identificacion")
                        .IsRequired()
                        .HasMaxLength(15);

                    b.Property<string>("nombre_completo")
                        .IsRequired()
                        .HasMaxLength(65);

                    b.Property<int>("semestre");

                    b.HasKey("id_estudiante");

                    b.HasIndex("identificacion")
                        .IsUnique();

                    b.ToTable("Estudiante");
                });
#pragma warning restore 612, 618
        }
    }
}
